/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stfciz.aws.ec2.ui;

import com.stfciz.aws.ec2.data.EC2Instance;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Bellevue
 */
public class EC2InstanceCellComponent extends javax.swing.JPanel {

    private EC2InstancesTableEventHandler ec2InstancesTableEventHandler;

    private EC2Instance ec2Instance;

    /**
     * Creates new form EC2InstanceTabPanel
     */
    public EC2InstanceCellComponent() {
        initComponents();
    }

    /**
     *
     * @param ec2Instance
     * @param ec2InstancesTableEventHandler
     */
    public EC2InstanceCellComponent(EC2InstancesTableEventHandler ec2InstancesTableEventHandler) {
        this();
        this.ec2InstancesTableEventHandler = ec2InstancesTableEventHandler;
    }

    /**
     *
     * @param ec2Instance
     */
    public void setEC2Instance(EC2Instance ec2Instance) {
        this.ec2Instance = ec2Instance;
        binding();
    }

    /**
     *
     */
    private void binding() {
        this.id.setText(this.ec2Instance.getId());
        this.name.setText(this.ec2Instance.getName());
        this.publicDnsName.setText(this.ec2Instance.getPublicDnsName());
        this.status.setText(this.ec2Instance.getStatus());
        this.publicDnsName.setText(this.ec2Instance.getPublicDnsName());
        displayActionState();
    }

    /**
     *
     */
    private void displayActionState() {
        /*
          0 : pending
         16 : running
         32 : shutting-down
         48 : terminated
         64 : stopping
         80 : stopped
         */
        if (80 == this.ec2Instance.getStatusCode()) {
            this.btnAction.setText("Start");
            this.btnAction.setActionCommand("start");
           
            this.status.setForeground(Color.WHITE);
            this.status.setBackground(Color.RED);
            this.status.setOpaque(true);
            this.status.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        } else if (16 == this.ec2Instance.getStatusCode()) {
            this.btnAction.setText("Stop");
            this.btnAction.setActionCommand("stop");
            
            this.status.setForeground(Color.BLACK);
            this.status.setBackground(Color.GREEN);
            this.status.setOpaque(true);
            this.status.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        } else {
            this.btnAction.setText("Refresh");
            this.btnAction.setActionCommand("refresh");
            
            this.status.setForeground(Color.BLACK);
            this.status.setBackground(this.getBackground());
            this.status.setOpaque(false);
            this.status.setBorder(null);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    id = new javax.swing.JLabel();
    name = new javax.swing.JLabel();
    btnAction = new javax.swing.JButton();
    status = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    publicDnsName = new javax.swing.JTextArea();

    jLabel1.setText("jLabel1");

    jTextField1.setText("jTextField1");

    setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

    id.setText("id");

    name.setText("name");

    btnAction.setText("jButton1");
    btnAction.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnActionActionPerformed(evt);
      }
    });

    status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    status.setText("status");
    status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    publicDnsName.setColumns(20);
    publicDnsName.setRows(5);
    jScrollPane1.setViewportView(publicDnsName);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addGap(4, 4, 4)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(name)
            .addGap(2, 2, 2)
            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(btnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(status)))
        .addGap(2, 2, 2))
    );
  }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        this.ec2InstancesTableEventHandler.action(evt.getActionCommand(), this.ec2Instance);
    }//GEN-LAST:event_btnActionActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAction;
  private javax.swing.JLabel id;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JLabel name;
  private javax.swing.JTextArea publicDnsName;
  private javax.swing.JLabel status;
  // End of variables declaration//GEN-END:variables
}
